apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-epic-nfs-storage-class  # Name of the StorageClass
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # Annotation to indicate if this is the default StorageClass
  labels:
    app: nfs-provisioner  # Label to identify the application associated with this StorageClass
provisioner: kubernetes.io/nfs  # Provisioner responsible for creating the NFS storage
reclaimPolicy: Retain  # Specifies the reclaim policy for released PVs to retain the data
allowVolumeExpansion: true  # Enables volume expansion for PersistentVolumes using this StorageClass
volumeBindingMode: Immediate  # Indicates immediate binding of PersistentVolumes
mountOptions:
  - vers=4.1  # Mount options to be used when mounting the NFS volume
parameters:
  server: 192.168.128.81  # IP address of the NFS server
  path: /KubCluster  # Path on the NFS server to be used for storage
