apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwardenrs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: your-storage-class-name
  hostPath:
    path: /home/serveradmin   # Update the path according to your cluster's file system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwardenrs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: your-storage-class-name
  volumeName: bitwardenrs-pv
