apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwardenrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwardenrs
  template:
    metadata:
      labels:
        app: bitwardenrs
    spec:
      containers:
        - name: bitwardenrs
          image: vaultwarden/server
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: bitwardenrs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bitwardenrs-service
spec:
  selector:
    app: bitwardenrs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100
  type: LoadBalancer
