apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /Backups
    server: 192.168.128.81
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
