apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
        - name: bitwarden
          image: vaultwarden/server
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: bitwarden-data
              mountPath: /data
      volumes:
        - name: bitwarden-data
          persistentVolumeClaim:
            claimName: bitwarden-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
spec:
  selector:
    app: bitwarden
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
