# bitwardenrs-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwardenrs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.128.81
    path: /Backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwardenrs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
