apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      initContainers:
        - name: change-ownership
          image: busybox
          command: ["chown", "-R", "1000:1000", "/app/data"]
          volumeMounts:
            - name: kuma-data
              mountPath: /app/data
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: kuma-data
              mountPath: /app/data
      volumes:
        - name: kuma-data
          persistentVolumeClaim:
            claimName: kuma
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
spec:
  selector:
    app: uptime-kuma
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
