apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-backups
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.81
    path: /Backups

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-config
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.81
    path: /Config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-databases
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.81
    path: /Databases

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mediashare
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.81
    path: /MediaShare

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-backups
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-databases
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mediashare
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
