apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksonic-air-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booksonic-air
  template:
    metadata:
      labels:
        app: booksonic-air
    spec:
      containers:
        - name: booksonic-air
          image: lscr.io/linuxserver/booksonic-air:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Denver"
            - name: CONTEXT_PATH
              #value: "url-base" # optional
          ports:
            - containerPort: 4040
          volumeMounts:
            - name: nfs
              mountPath: "/config"
            - name: nfs
              mountPath: "/books"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs       
        
---
apiVersion: v1
kind: Service
metadata:
  name: booksonic-air-service
spec:
  selector:
    app: booksonic-air
  ports:
    - port: 4040
      targetPort: 4040
  type: LoadBalancer
