apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksonic-air
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booksonic-air
  template:
    metadata:
      labels:
        app: booksonic-air
    spec:
      containers:
        - name: booksonic-air
          image: linuxserver/booksonic-air:latest
          env:
            - name: TZ
              value: "America/Denver"
          volumeMounts:
            - name: audiobooks-volume
              mountPath: /audiobooks
            - name: config-volume
              mountPath: /config
          ports:
            - containerPort: 4040
              protocol: TCP
          securityContext:
            privileged: true  # Add this line to enable privileged mode
      volumes:
        - name: audiobooks-volume
          persistentVolumeClaim:
            claimName: booknfs
        - name: config-volume
          persistentVolumeClaim:
            claimName: bslocal
      
---
apiVersion: v1
kind: Service
metadata:
  name: booksonic-air
  namespace: default
spec:
  selector:
    app: booksonic-air
  ports:
  - protocol: TCP
    port: 4040
    targetPort: 4040
  type: LoadBalancer
