apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-epic-pvc  # Name of the PVC
spec:
  storageClassName: my-epic-nfs-storage-class  # Name of the StorageClass to use for provisioning
  accessModes:
    - ReadWriteMany  # Access mode for the PVC, allowing multiple Pods to read and write concurrently
  resources:
    requests:
      storage: 10Gi  # Requested storage size for the PVC, specifying 10 Gigabytes
