apiVersion: v1
kind: PersistentVolume
metadata:
  name: emlocal
spec:
  capacity:
    storage: 256Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/myapp/config
  persistentVolumeReclaimPolicy: Retain

