apiVersion: v1
kind: PersistentVolume
metadata:
  name: emulatorjs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.128.200
    path: /proxcluster/emulatorjs
