apiVersion: v1
kind: PersistentVolume
metadata:
  name: booknfs
spec:
  capacity:
    storage: 256Gi
  accessModes:
  - ReadWriteMany
  storageClassName: booknfs
  nfs:
    server: 192.168.128.200
    path: /proxcluster/booksonic
  persistentVolumeReclaimPolicy: Retain
    
