apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booksonic-air-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: booksonic-air
