apiVersion: apps/v1
kind: Deployment
metadata:
  name: emulatorjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emulatorjs
  template:
    metadata:
      labels:
        app: emulatorjs
    spec:
      containers:
        - name: emulatorjs
          image: lscr.io/linuxserver/emulatorjs:latest
          ports:
            - name: port-3000
              containerPort: 3000
            - name: port-80
              containerPort: 80
            - name: port-4001
              containerPort: 4001 #optional
          env:
            - name: TZ
              value: "America/Denver"
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: data-volume
              mountPath: /data
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: emlocal
        - name: data-volume
          persistentVolumeClaim:
            claimName: emulatorjs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: emulatorjs
spec:
  type: LoadBalancer
  selector:
    app: emulatorjs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: port-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: port-4001
      protocol: TCP
      port: 4001
      targetPort: 4001 #optional
